version: '3.8'

services:
  local-localstack:
    container_name: local-localstack
    image: localstack/localstack:1.2.0
    environment:
      DEBUG: 1
      INIT_SCRIPTS_PATH: /docker-entrypoint-initaws.d
    volumes:
      - $PWD/localstack:/docker-entrypoint-initaws.d
    ports:
      - 4566:4566
    networks:
      - sls

networks:
  sls:
