// Code generated by mockery v2.21.1. DO NOT EDIT.

package mocks

import (
	context "context"
	core "sls-go/src/items/core"

	mock "github.com/stretchr/testify/mock"
)

// ItemsStreamer is an autogenerated mock type for the ItemsStreamer type
type ItemsStreamer struct {
	mock.Mock
}

// StreamItems provides a mock function with given fields: ctx, key, importChannel
func (_m *ItemsStreamer) StreamItems(ctx context.Context, key string, importChannel chan<- core.Item) error {
	ret := _m.Called(ctx, key, importChannel)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, chan<- core.Item) error); ok {
		r0 = rf(ctx, key, importChannel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewItemsStreamer interface {
	mock.TestingT
	Cleanup(func())
}

// NewItemsStreamer creates a new instance of ItemsStreamer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewItemsStreamer(t mockConstructorTestingTNewItemsStreamer) *ItemsStreamer {
	mock := &ItemsStreamer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
